version: "3.9"
networks:
  runalytics-network:
    name: runalytics-network
    driver: bridge

services:
  runanalytics-backend:
    build: 
      context: .
      target: development
    container_name: runanalytics-backend
    image: runanalytics-backend:latest
    environment:
      - TZ=America/Sao_Paulo
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=runalytics
      - JWT_SECRET=runalytics
    volumes:
      - ${PWD}:/app
    ports:
      - 3000:3000
    depends_on:
      - postgres
    networks:
      - runalytics-network

  postgres:
    image: bitnami/postgresql
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=runalytics
    networks:
      - runalytics-network
    